const apiUrl = {
    install (Vue) {
        Vue.prototype.$apiUrl = this;
    },
    //登录-退出
    ACCOUNT_login: '/api/user/login',
    ACCOUNT_logout: '/api/user/logout',
    ACCOUNT_userInfo: '/api/user/userInfo',
    //基础获取菜单和用户信息
    ACCOUNT_userInfo: '/api/user/userInfo',
    ACCOUNT_menu: '/api/user/menu',
    PUBLIC_GetConfig: '/api/public/config/getConfig',
    PUBLIC_GetIntervalList: '/api/public/config/getIntervalList',


    ACCOUNT_editAccount: '/api/userAccount/editAccount',
    ACCOUNT_getAccountList: '/api/userAccount/list',
    ACCOUNT_deleteAccount: '/api/userAccount/deleteAccout',
    ACCOUNT_create: '/api/userAccount/create',
    ACCOUNT_checkEmail: '/api/userAccount/checkEmail',
    ACCOUNT_resetPassowrd: '/api/userAccount/resetPassword',
    ACCOUNT_register: '/api/userAccount/merchantRegister',
    ACCOUNT_checkMerchant: '/api/userAccount/checkMerchant',
    ACCOUNT_checkPhone: '/api/userAccount/checkPhone',
    ACCOUNT_checkPwdCode: '/api/userAccount/checkPwdCode',
    ACCOUNT_passwordCode: '/api/userAccount/pwdCode',
    ACCOUNT_registerCode: '/api/userAccount/regCode',
    ACCOUNT_setPassword: '/api/userAccount/setPassword',
    ACCOUNT_phoneCode: '/api/userAccount/phoneCode',
    ACCOUNT_changePhone: '/api/userAccount/changePhone',

    //商户管理 --- 商户
    MERCHANT_list: '/api/merchant/merchantList',
    MERCHANT_del: '/api/merchant/merchantDel',
    MERCHANT_canMouelList: '/api/merchant/moduleList',
    MERCHANT_setModule: '/api/merchant/setModule',

    //商户管理 --- 角色
    SYSTEM_roleList: '/api/merchant/systemRoleList',
    SYSTEM_allModule: '/api/merchant/systemModules',
    SYSTEM_role: '/api/merchant/systemRole',
    SYSTEM_editRole: '/api/merchant/editSystemRole',
    SYSTEM_delRole: '/api/merchant/delSystemRole',
    SYSTEM_createRole: '/api/merchant/createSystemRole',
    SYSTEM_moduleAuth: '/api/merchant/moduleAuth',

    //商户管理 --- key
    SYSTEM_keyList: '/api/merchant/systemKeyList',
    SYSTEM_key: '/api/merchant/systemKey',
    SYSTEM_createKey: '/api/merchant/createKey',
    SYSTEM_editKey: '/api/merchant/editKey',
    SYSTEM_delKey: '/api/merchant/delKey',
    SYSTEM_changeDisableStatus: '/api/merchant/changeDisableStatus',

    //商户管理 --- 模块
    SYSTEM_moduleList: '/api/merchant/systemModuleList',
    SYSTEM_module: '/api/merchant/systemModule',
    SYSTEM_createModule: '/api/merchant/createModule',
    SYSTEM_delModule: '/api/merchant/delModule',
    SYSTEM_editModule: '/api/merchant/editModule',

    //商户管理 --- 菜单
    MENU_list: '/api/merchant/menuList',
    SYSTEM_menuinfo: '/api/merchant/systemMenuinfo',
    SYSTEM_menu: '/api/merchant/systemMenu',
    SYSTEM_editMenu: '/api/merchant/editMenu',
    SYSTEM_delMenu: '/api/merchant/delMenu',
    SYSTEM_getSubmenu: '/api/merchant/getSubmenu',
    SYSTEM_addSubmenu: '/api/merchant/addSubmenu',
    SYSTEM_addMenu: '/api/merchant/addMenu',


    //后台账号管理
    ADMIN_accountLsit: '/api/admin/acccountList',
    ADMIN_accountCreate: '/api/admin/accountCreate',
    ADMIN_checkEmail: '/api/admin/checkEmail',
    ADMIN_changeAccountStatus: '/api/admin/changeAccountStatus',
    ADMIN_canAuthList: '/api/admin/canAuthList',
    ADMIN_setAuth: '/api/admin/setAuth',
    ADMIN_setSuperAdmin: '/api/admin/setSuperAdmin',


    //后台管理 --- 角色
    ADMIN_roleList: '/api/admin/systemRoleList',
    ADMIN_allModule: '/api/admin/systemModules',
    ADMIN_role: '/api/admin/systemRole',
    ADMIN_editRole: '/api/admin/editSystemRole',
    ADMIN_delRole: '/api/admin/delSystemRole',
    ADMIN_createRole: '/api/admin/createSystemRole',
    ADMIN_moduleAuth: '/api/admin/moduleAuth',

    //后台管理 --- key
    ADMIN_keyList: '/api/admin/systemKeyList',
    ADMIN_key: '/api/admin/systemKey',
    ADMIN_createKey: '/api/admin/createKey',
    ADMIN_editKey: '/api/admin/editKey',
    ADMIN_delKey: '/api/admin/delKey',
    ADMIN_changeDisableStatus: '/api/admin/changeDisableStatus',

    //后台管理 --- 模块
    ADMIN_moduleList: '/api/admin/systemModuleList',
    ADMIN_module: '/api/admin/systemModule',
    ADMIN_createModule: '/api/admin/createModule',
    ADMIN_delModule: '/api/admin/delModule',
    ADMIN_editModule: '/api/admin/editModule',

    //后台管理 --- 菜单
    ADMIN_menuList: '/api/admin/menuList',
    ADMIN_menuinfo: '/api/admin/systemMenuinfo',
    ADMIN_menu: '/api/admin/systemMenu',
    ADMIN_editMenu: '/api/admin/editMenu',
    ADMIN_delMenu: '/api/admin/delMenu',
    ADMIN_getSubmenu: '/api/admin/getSubmenu',
    ADMIN_addSubmenu: '/api/admin/addSubmenu',
    ADMIN_addMenu: '/api/admin/addMenu',

    //系统管理 -- 操作日志
    OPERATION_getLogList: '/api/system/operationLogList',

    //系统管理 -- api日志
    API_getLogList: '/api/system/apiLogList',
    API_getOpenModule: '/api/system/getOpenModule',

    //支付中心
    ADMINPAY_getChannel: '/api/adminPay/getChannel',
    ADMINPAY_getErrorCodeList: '/api/adminPay/getErrorCodeList',
    ADMINPAY_getSaasCodeAndMsg: '/api/adminPay/getSaasCodeAndMsg',
    ADMINPAY_createChannelCode: '/api/adminPay/createChannelCode',
    ADMINPAY_delChannelCodeMapping: '/api/adminPay/delChannelCodeMapping',
    ADMINPAY_editChannelCodeMapping: '/api/adminPay/editChannelCodeMapping',
    ADMINPAY_getCodeMappingInfo: '/api/adminPay/getCodeMappingInfo',

    //后台-支付中心
    //查看流水
    ADMIN_pay_flow: '/api/adminPay/payFlow',
    ADMIN_pay_bankAll: '/api/adminPay/bankAll',
    ADMIN_pay_bankList: '/api/adminPay/bankList',
    ADMIN_pay_bankAdd: '/api/adminPay/bankAdd',
    ADMIN_pay_bankDisable: '/api/adminPay/bankDisable',
    ADMIN_pay_platform: '/api/adminPay/platform',
    ADMIN_bankMaintain: '/api/adminPay/bankMaintain',
    ADMIN_bankMaintainCreate: '/api/adminPay/bankMaintainAdd',

    PERMISSION_getModules: '/api/permission/modules',
    PERMISSION_canAuthList: '/api/permission/canAuthList',
    PERMISSION_setAuth: '/api/permission/setAuth',
    PERMISSION_moduleAuth: '/api/permission/moduleAuth',
    PERMISSION_create: '/api/permission/create',
    PERMISSION_list: '/api/permission/list',
    PERMISSION_role: '/api/permission/role',
    PERMISSION_editRole: '/api/permission/editRole',
    PERMISSION_delRole: '/api/permission/delRole',
    PERMISSION_menu: '/api/user/menu',
    PERMISSION_appkeyList: '/api/permission/appkeyList',
    PERMISSION_appkeyCreate: '/api/permission/appkeyCreate',
    PERMISSION_appkeyDel: '/api/permission/appkeyDel',
    PERMISSION_getAppkeyAuth: '/api/permission/getAppkeyAuth',
    PERMISSION_setAppkeyAuth: '/api/permission/setAppkeyAuth',
    PERMISSION_allOpenAuth: '/api/permission/allOpenAuth',

    SMS_getConfig: '/api/sms/config/getConfig',
    SMS_getAllSignByChannel: '/api/sms/sign/allsignListByChannel',
    SMS_getSignDetail: '/api/sms/sign/signdetail',
    SMS_addSign: '/api/sms/sign/addsign',
    SMS_modifysign: '/api/sms/sign/modifysign',
    SMS_getSignList: '/api/sms/sign/allsign',
    SMS_delsign: '/api/sms/sign/delsign',
    SMS_operatorsign: '/api/sms/sign/operatorsign',

    PUSH_getConfig: '/api/push/channel/getConfig',
    PUSH_getProviderInfo: '/api/push/channel/providerInfo',
    PUSH_getAllChannel: '/api/push/channel/all',
    PUSH_addChannel: '/api/push/channel/add',
    PUSH_getChannelList: '/api/push/channel/list',
    PUSH_operatorChannel: '/api/push/channel/operator',
    PUSH_delChannel: '/api/push/channel/del',
    PUSH_getChannelDetai: '/api/push/channel/detail',
    PUSH_modifyChannel: '/api/push/channel/modify',
    PUSH_taskList: '/api/push/task/list',
    PUSH_delTask: '/api/push/task/del',
    PUSH_approveTask: '/api/push/task/approve',
    PUSH_getPushParams: '/api/push/task/pushParams',
    PUSH_taskInfo: '/api/push/task/info',
    PUSH_tashCreate: '/api/push/task/create',
    PUSH_tashModify: '/api/push/task/modify',

    PUSH_getBlacklist: '/api/push/blacklist/list',
    PUSH_addBlacklist: '/api/push/blacklist/add',
    PUSH_delBlacklist: '/api/push/blacklist/del',

    SMS_getChannelBySign: '/api/sms/channel/channelBySign',
    SMS_getChannelBySignChoose: '/api/sms/channel/channelBySignChoose',

    SMS_getProviderInfo: '/api/sms/channel/providerInfo',
    SMS_getAllChannel: '/api/sms/channel/all',
    SMS_addChannel: '/api/sms/channel/add',
    SMS_getChannelList: '/api/sms/channel/list',
    SMS_operatorChannel: '/api/sms/channel/operator',
    SMS_delChannel: '/api/sms/channel/del',
    SMS_getChannelDetai: '/api/sms/channel/detail',
    SMS_modifyChannel: '/api/sms/channel/modify',
    SMS_getChannelSignList: '/api/sms/channel/channelSignlist',
    SMS_getSignFixList: '/api/sms/channel/signFixlist',

    SMS_addTemplate: '/api/sms/template/addtemplate',
    SMS_getTemplateList: '/api/sms/template/alltemplate',
    SMS_getTemplates: '/api/sms/template/getTemplates',
    SMS_operatorTemplate: '/api/sms/template/operatortemplate',
    SMS_delTemplate: '/api/sms/template/deltemplate',
    SMS_getTemplateDetail: '/api/sms/template/detail',
    SMS_modifyTemplate: '/api/sms/template/modifytemplate',
    SMS_getAllTemplate: '/api/sms/template/templateall',
    SMS_modifyTemplateStatus: '/api/sms/template/modifytemplatestatus',

    SMS_addTask: '/api/sms/msgtask/add',
    SMS_getTaskStatus: '/api/sms/msgtask/getTaskStatus',
    SMS_getTaskList: '/api/sms/msgtask/getTaskList',
    SMS_getTaskDetail: '/api/sms/msgtask/getTaskDetail',
    SMS_taskCheck: '/api/sms/msgtask/check',
    SMS_delTask: '/api/sms/msgtask/del',
    SMS_taskSend: '/api/sms/msgtask/sendtask',
    SMS_taskRecordList: '/api/sms/msgtask/taskRecordList',
    SMS_getReportTaskData: '/api/sms/report/getTaskData',
    SMS_getReportTimeGran: '/api/sms/report/getTimeGranularity',

    SMS_getDJPackageList: '/api/sms/dianjin/packageList',
    SMS_getDJPackageAdd: '/api/sms/dianjin/packageAdd',
    SMS_djPackageRefresh: '/api/sms/dianjin/packageRefresh',
    SMS_getDJSignList: '/api/sms/dianjin/signList',
    SMS_djSignAdd: '/api/sms/dianjin/signAdd',
    SMS_djSignRefresh: '/api/sms/dianjin/signRefresh',
    SMS_getDJSignDetail: '/api/sms/dianjin/signDetail',
    SMS_djSignModify: '/api/sms/dianjin/signModify',
    SMS_getDJTemplateList: '/api/sms/dianjin/templateList',
    SMS_djTemplateAdd: '/api/sms/dianjin/templateAdd',
    SMS_djTemplateRefresh: '/api/sms/dianjin/templateRefresh',
    SMS_getDJTemplateDetail: '/api/sms/dianjin/templateDetail',
    SMS_djTemplateModify: '/api/sms/dianjin/templateModify',
    SMS_getDJLaunchList: '/api/sms/dianjin/launchList',
    SMS_djLaunchAdd: '/api/sms/dianjin/launchAdd',
    SMS_djLaunchRefresh: '/api/sms/dianjin/launchRefresh',
    SMS_getDJLaunchDetail: '/api/sms/dianjin/launchDetail',
    SMS_djLaunchModify: '/api/sms/dianjin/launchModify',

    SMS_getGroupByTmpl: '/api/sms/report/groupByTmpl',
    SMS_getTemplateSuccessNum: '/api/sms/report/templateSuccessNum',
    SMS_getTemplateSuccessRate: '/api/sms/report/templateSuccessRate',
    SMS_getTemplateTouchRate: '/api/sms/report/templateTouchRate',
    SMS_getFcilitatorSuccessNum: '/api/sms/report/fcilitatorSuccessNum',
    SMS_getFcilitatorSuccessRate: '/api/sms/report/fcilitatorSuccessRate',
    SMS_getFcilitatorTouchRate: '/api/sms/report/fcilitatorTouchRate',

    SMS_getBlacklist: '/api/sms/blacklist/list',
    SMS_addBlacklist: '/api/sms/blacklist/add',
    SMS_delBlacklist: '/api/sms/blacklist/del',

    SMS_alarmList: '/api/sms/alarm/list',
    SMS_alarmChangeStatus: '/api/sms/alarm/changeStatus',
    SMS_alarmUpdate: '/api/sms/alarm/update',
    SMS_alarmView: '/api/sms/alarm/view',
    SMS_alarmAdd: '/api/sms/alarm/add',
    SMS_alarmConfig: '/api/sms/alarm/config',

    //短信帐户余额查询
    SMS_balanceList: '/api/sms/alarm/balanceList',
    SMS_balanceUpdate: '/api/sms/alarm/balanceUpdate',

    PAY_config_errorlist: '/api/pay/error/list',
    PAY_all_errorlist: '/api/pay/error/list-all',
    PAY_config_productlist: '/api/pay/product/list',
    PAY_config_productadd: '/api/pay/product/add',
    PAY_config_productdetail: '/api/pay/product/detail',
    PAY_config_productupdate: '/api/pay/product/update',
    PAY_config_bankall: '/api/pay/bank/all',
    PAY_config_bankadd: '/api/pay/bank/add',
    PAY_config_banklist: '/api/pay/bank/list',
    PAY_platformSys: '/api/pay/platform/sys',
    PAY_platformFee: '/api/pay/platform/feeinfo',
    PAY_platformBankList: '/api/pay/platform/banklist',
    PAY_platformBankAdd: '/api/pay/platform/addbank',
    PAY_platformBankEdit: '/api/pay/platform/editbank',
    PAY_platformBankDelete: '/api/pay/platform/deletebank',
    PAY_platformAdd: '/api/pay/platform/add',
    PAY_platformParams: '/api/pay/platform/params',

    PAY_platformList: '/api/pay/platform/list',
    PAY_platformModify: '/api/pay/platform/modify',
    PAY_platformDetail: '/api/pay/platform/detail',
    PAY_platformErrorList: '/api/pay/platform/errorlist',

    PAY_routeParams: '/api/pay/route/params',
    PAY_routeAdd: '/api/pay/route/create',
    PAY_routeList: '/api/pay/route/list',
    PAY_routeOperatorStatus: '/api/pay/route/changeStatus',
    PAY_routeDetail: '/api/pay/route/detail',
    PAY_routeEdit: '/api/pay/route/edit',
    PAY_routePriority: '/api/pay/route/priority',
    PAY_routePriorityEdit: '/api/pay/route/priorityEdit',

    PAY_ruleList: '/api/pay/rule/list',
    PAY_ruleParams: '/api/pay/rule/params',
    PAY_ruleProductFields: '/api/pay/rule/productFields',
    PAY_ruleCreate: '/api/pay/rule/create',
    PAY_ruleOperatorStatus: '/api/pay/rule/changeStatus',
    PAY_ruleDel: '/api/pay/rule/del',
    PAY_ruleDetail: '/api/pay/rule/detail',
    PAY_ruleEdit: '/api/pay/rule/edit',

    PAY_dataAuthLog: '/api/pay/data/auth',
    PAY_dataPayLog: '/api/pay/data/pay',
    PAY_dataRemitLog: '/api/pay/data/remit',
    PAY_dataPlatformByBiz: '/api/pay/data/platformByBiz',
    PAY_dataBindLog: '/api/pay/data/bind',
    PAY_unbindCard: '/api/pay/data/unbind',
    Pay_dataOrderLogs: '/api/pay/data/orderLog',
    Pay_dataProductList: '/api/pay/data/productList',
    Pay_dataBankList: '/api/pay/data/bankList',
    PAY_getOverallReport: '/api/pay/data/overallReport',
    PAY_getPayTypeList: '/api/pay/data/payTypeList',
    PAY_getPlatformReport: '/api/pay/data/platformReport',
    PAY_getMoneyReport: '/api/pay/data/moneyReport',
    PAY_getPlatformMoneyReport: '/api/pay/data/platformMoneyReport',
    PAY_operationLog: '/api/pay/data/operationLog',
    PAY_changeTransactionStatus: '/api/pay/data/changeTranscationStatus',
    PAY_transactionResend: '/api/pay/data/transactionResend',
    //打款和支付所有通道
    PAY_dataPlatformPayRemit: '/api/pay/data/platformPayRemit',

    //工作台
    PAY_getWorkbenchList: '/api/pay/workbench/list',
    PAY_getWorkbenchAdd: '/api/pay/workbench/add',
    PAY_dataPlatformByTransfer: '/api/pay/workbench/platformByTransfer',
    PAY_getPlatformByInfo: '/api/pay/workbench/getPlatformByInfo',

    //告警列表
    PAY_alarmList: '/api/pay/alarm/list',
    PAY_alarmChangeStatus: '/api/pay/alarm/changeStatus',
    PAY_alarmUpdate: '/api/pay/alarm/update',
    PAY_alarmView: '/api/pay/alarm/view',
    PAY_alarmAdd: '/api/pay/alarm/add',
    PAY_alarmConfig: '/api/pay/alarm/config',

    SETTING_getAccount: '/api/userAccount/personalData',
    SETTING_editAccount: '/api/userAccount/editPersonalData',
    SETTING_password: '/api/userAccount/modifyPwd',

    CONFCENTER_typeList: '/api/confcenter/datatype/typeList',
    CONFCENTER_addType: '/api/confcenter/datatype/addType',
    CONFCENTER_whiteList: '/api/confcenter/white/list',
    CONFCENTER_whiteListAddData: '/api/confcenter/white/addData',
    CONFCENTER_whiteListmodifyData: '/api/confcenter/white/modifyData',
    CONFCENTER_whiteDetail: '/api/confcenter/white/detail',
    CONFCENTER_blackList: '/api/confcenter/black/list',
    CONFCENTER_blackListAddData: '/api/confcenter/black/addData',
    CONFCENTER_blackListmodifyData: '/api/confcenter/black/modifyData',
    CONFCENTER_blackDetail: '/api/confcenter/black/detail',
    CONFCENTER_NstypeList: '/api/confcenter/nstype/typeList',
    CONFCENTER_NsaddType: '/api/confcenter/nstype/addType',
    CONFCENTER_NsRemoveType: '/api/confcenter/nstype/removeType',
    CONFCENTER_NsDataType: '/api/confcenter/nstype/dataType',
    CONFCENTER_NsModifyType: '/api/confcenter/nstype/modifyType',

    CONFCENTER_NsdataList: '/api/confcenter/nsdata/dataList',
    CONFCENTER_NsKeyType: '/api/confcenter/config/getConfig',
    CONFCENTER_NsaddData: '/api/confcenter/nsdata/addData',
    CONFCENTER_NsRemoveData: '/api/confcenter/nsdata/removeData',
    CONFCENTER_NsData: '/api/confcenter/nsdata/getDataDetail',
    CONFCENTER_NsmodifyData: '/api/confcenter/nsdata/modifyData',

    LOG_operationList: '/api/log/operation/list',
    LOG_openApiChart: '/api/log/api/chart',
    LOG_openApiList: '/api/log/api/list',
    LOG_getTimeGran: '/api/log/api/timeGran',

    RISKCONTROL_GetStatRuleList: '/api/riskcontrol/rule/getStatRuleList',
    RISKCONTROL_AddStatRuleList: '/api/riskcontrol/statics/addStatRuleList',
    RISKCONTROL_GetStatRuleReportList: '/api/riskcontrol/rule/getStatRuleReportList',
    RISKCONTROL_GetStatRuleReportDetail: '/api/riskcontrol/rule/getStatRuleReportDetail',
    RISKCONTROL_ModifyStatRuleList: '/api/riskcontrol/statics/modifyStatRuleList',
    RISKCONTROL_GetRuleReportData: '/api/riskcontrol/statics/getRuleReportData',
    RISKCONTROL_GetTreeList: '/api/riskcontrol/statics/getTreeList',
    RISKCONTROL_GetTreeData: '/api/riskcontrol/statics/getTreeData',
    RISKCONTROL_AddDashBoard: '/api/riskcontrol/rule/addDashBoard',
    RISKCONTROL_GetSnapInfo: '/api/riskcontrol/rule/getSnapInfo',
    RISKCONTROL_GetSnapBaseRuleData: '/api/riskcontrol/rule/getSnapBaseRuleData',
    RISKCONTROL_GetSnapRuleExpList: '/api/riskcontrol/rule/getSnapRuleExpList',
    RISKCONTROL_GetAllTrees: '/api/riskcontrol/rule/getAllTrees',
    RISKCONTROL_GetTreeStructure: '/api/riskcontrol/rule/getTreeStructure',
    RISKCONTROL_alarmList: '/api/riskcontrol/alarm/list',
    RISKCONTROL_alarmChangeStatus: '/api/riskcontrol/alarm/changeStatus',
    RISKCONTROL_alarmUpdate: '/api/riskcontrol/alarm/update',
    RISKCONTROL_alarmView: '/api/riskcontrol/alarm/view',
    RISKCONTROL_alarmAdd: '/api/riskcontrol/alarm/add',
    RISKCONTROL_alarmConfig: '/api/riskcontrol/alarm/config',
    RISKCONTROL_DDlist: '/api/riskcontrol/DDlist',
    RISKCONTROL_DDcreate: '/api/riskcontrol/DDcreate',
    RISKCONTROL_DDupdate_column: '/api/riskcontrol/DDUpdateFeature',
    RISKCONTROL_DDview: '/api/riskcontrol/DDview',
    RISKCONTROL_DDchangeFeatureStatus: '/api/riskcontrol/DDChangeFeatureStatus',
    RISKCONTROL_GetRuleReportDataResult: '/api/riskcontrol/statics/getRuleReportDataResult',
    RISKCONTROL_ResultDistributeRecordMore: '/api/riskcontrol/statics/getRuleReportDataResultMore',
    RISKCONTROL_getFeatureStat: '/api/riskcontrol/statics/getFeatureStat',
    RISKCONTROL_apiList: '/api/riskcontrol/rule/getApiLogList',

    RCM_getRuleList: '/api/riskcontrol/list',
    RCM_getRuleInfo: '/api/riskcontrol/info',
    RCM_addRuleInfo: '/api/riskcontrol/add',
    RCM_copyRuleInfo: '/api/riskcontrol/copy',
    RCM_editRuleInfo: '/api/riskcontrol/editInfo',
    RCM_deleteRuleInfo: '/api/riskcontrol/deleteInfo',
    RCM_editRuleInfoResult: '/api/riskcontrol/editInfoResult',

    RCM_getMapRuleInfo: '/api/riskcontrol/getMapRuleInfo',
    RCM_getMapRuleList: '/api/riskcontrol/getMapRuleList',
    RCM_addMapRuleInfo: '/api/riskcontrol/addMapRuleInfo',
    RCM_editMapRuleInfo: '/api/riskcontrol/editMapRuleInfo',
    RCM_exchangeMapRuleOrder: '/api/riskcontrol/exchangeMapRuleOrder',
    RCM_checkRemoteFeature: '/api/riskcontrol/checkRemoteFeature',
    RCM_deleteMapRuleInfo: '/api/riskcontrol/deleteMapRuleInfo',

    RCM_getBaseRuleList: '/api/riskcontrol/baseRuleList',
    RCM_getBaseRuleInfo: '/api/riskcontrol/baseRuleInfo',
    RCM_editBaseRuleInfo: '/api/riskcontrol/editRuleInfo',
    RCM_addBaseRuleInfo: '/api/riskcontrol/addRuleInfo',
    RCM_deleteBaseRuleInfo: '/api/riskcontrol/deleteRuleInfo',

    RCM_getTemplateList: '/api/riskcontrol/templateList',
    RCM_getTemplateMap: '/api/riskcontrol/templateMap',
    RCM_getTemplateInfo: '/api/riskcontrol/templateInfo',
    RCM_editTemplateInfo: '/api/riskcontrol/editTemplateInfo',
    RCM_addTemplateInfo: '/api/riskcontrol/addTemplateInfo',
    RCM_deleteTemplateInfo: '/api/riskcontrol/deleteTemplateInfo',

    RCM_addTemplateField: '/api/riskcontrol/addTemplateField',
    RCM_editTemplateField: '/api/riskcontrol/editTemplateField',
    RCM_deleteTemplateField: '/api/riskcontrol/deleteTemplateField',
    MODULE_getOpenModules: '/api/module/getOpenModules',
    RCM_getDashBoardList: '/api/riskcontrol/rule/getDashBoardList',
    RCM_getRuleLog: '/api/riskcontrol/rule/getRuleLog',
    RCM_getAuthList: '/api/riskcontrol/getAuthList',
    RCM_changeAuth: '/api/riskcontrol/changeAuth',
    RCM_getRuleOwner: '/api/riskcontrol/getRuleOwner',
    RCM_getRuleListAuth: '/api/riskcontrol/getRuleListAuth',
    RCM_getAllUser: '/api/riskcontrol/getAllUser',
    RCM_addUserAuth: '/api/riskcontrol/addUserAuth',
    RCM_testTree: '/api/riskcontrol/testTree',
    RCM_getAllFeature: '/api/riskcontrol/getAllFeature',

    FEATURE_list: '/api/feature/list',
    FEATURE_upload: '/api/feature/upload',
    FEATURE_create: '/api/feature/create',
    FEATURE_update: '/api/feature/update',
    FEATURE_update_column: '/api/feature/updateFeature',
    FEATURE_config: '/api/feature/configFeature',
    FEATURE_changeFeatureType: '/api/feature/changeFeatureType',
    FEATURE_view: '/api/feature/view',

    FEATURE_daoList: '/api/feature/daoList',
    FEATURE_daoView: '/api/feature/daoView',
    FEATURE_daoCreate: '/api/feature/daoCreate',
    FEATURE_daoUpdate: '/api/feature/daoUpdate',
    FEATURE_changeFeatureStatus: '/api/feature/changeFeatureStatus',
    FEATURE_changeDaoStatus: '/api/feature/changeDaoStatus',
    FEATURE_updateFormat: '/api/feature/updateFormat',
    FEATURE_quickUpdateFormat: '/api/feature/quickUpdateFormat',
    FEATURE_expressionUpdate: '/api/feature/expressionUpdate',
    FEATURE_getAllFeatureDao: '/api/feature/getAllFeatureDao',
    FEATURE_demo: '/api/feature/demo',
    PUBLIC_downLoadSDK: '/api/public/config/downLoadSDK',

    //短链服务
    SHORTLINK_list: '/api/shortlink/list',
    SHORTLINK_add: '/api/shortlink/add',
    SHORTLINK_del: '/api/shortlink/del',
    SHORTLINK_log: '/api/shortlink/log',
    SHORTLINK_count: '/api/shortlink/count',

    //账户中心
    PAY_account_config_productlist: '/api/account/product/list',
    PAY_account_config_productadd: '/api/account/product/add',
    PAY_account_config_productdetail: '/api/account/product/detail',
    PAY_account_config_productupdate: '/api/account/product/update',



    //特征服务 - 模板
    ADMINFEATURE_getTemplateList: '/api/adminFeature/getTemplateList',
    ADMINFEATURE_editTemplateField: '/api/adminFeature/editTemplateField',
    ADMINFEATURE_addTemplateInfo: '/api/adminFeature/addTemplateInfo',
    ADMINFEATURE_deleteTemplateInfo: '/api/adminFeature/deleteTemplateInfo',
    ADMINFEATURE_editTemplateInfo: '/api/adminFeature/editTemplateInfo',
    ADMINFEATURE_getTemplateInfo: '/api/adminFeature/getTemplateInfo',

    //特征服务 - 数据源
    ADMINFEATURE_daoList: '/api/adminFeature/daoList',
    ADMINFEATURE_changeDaoStatus: '/api/adminFeature/changeDaoStatus',
    ADMINFEATURE_daoCreate: '/api/adminFeature/daoCreate',
    ADMINFEATURE_daoView: '/api/adminFeature/daoView',
    ADMINFEATURE_quickUpdateFormat: '/api/adminFeature/quickUpdateFormat',
    ADMINFEATURE_updateFormat: '/api/adminFeature/updateFormat',
    ADMINFEATURE_daoUpdate: '/api/adminFeature/daoUpdate',
    ADMINFEATURE_demo: '/api/adminFeature/demo',

    //特征服务 - 共享特征
    ADMINFEATURE_featureList: '/api/adminFeature/featureList',
    ADMINFEATURE_changeFeatureStatus: '/api/adminFeature/changeFeatureStatus',
    ADMINFEATURE_createFeature: '/api/adminFeature/createFeature',
    ADMINFEATURE_featureView: '/api/adminFeature/featureView',
    ADMINFEATURE_updateFeature: '/api/adminFeature/updateFeature',
    ADMINFEATURE_config: '/api/adminFeature/configFeature',
    ADMINFEATURE_changeFeatureType: '/api/adminFeature/changeFeatureType',
    ADMINFEATURE_getAllFeatureDao: '/api/adminFeature/getAllFeatureDao',
    ADMINFEATURE_expressionUpdate: '/api/adminFeature/expressionUpdate',


    //特征服务 - 共享规则
    ADMINFEATURE_addRuleInfo: '/api/adminFeature/addRuleInfo',
    ADMINFEATURE_getRuleList: '/api/adminFeature/ruleList',
    ADMINFEATURE_getTemplateMap: '/api/adminFeature/templateMap',
    ADMINFEATURE_deleteRuleInfo: '/api/adminFeature/deleteRuleInfo',
    ADMINFEATURE_getAllFeature: '/api/adminFeature/getAllFeature',
    ADMINFEATURE_getMapRuleList: '/api/adminFeature/getMapRuleList',
    ADMINFEATURE_editMapRuleInfo: '/api/adminFeature/editMapRuleInfo',
    ADMINFEATURE_addMapRuleInfo: '/api/adminFeature/addMapRuleInfo',
    ADMINFEATURE_getRuleInfo: '/api/adminFeature/getRuleInfo',
    ADMINFEATURE_testTree: '/api/adminFeature/testTree',
    ADMINFEATURE_editRuleInfo: '/api/adminFeature/editRuleInfo',
    ADMINFEATURE_editRuleInfoResult: '/api/adminFeature/editRuleInfoResult',
    ADMINFEATURE_getBaseRuleList: '/api/adminFeature/getBaseRuleList',
    ADMINFEATURE_GetStatRuleList: '/api/adminFeature/GetStatRuleList',
    ADMINFEATURE_copyRuleInfo: '/api/adminFeature/copyRuleInfo',
    ADMINFEATURE_exchangeMapRuleOrder: '/api/adminFeature/exchangeMapRuleOrder',
    ADMINFEATURE_deleteMapRuleInfo: '/api/adminFeature/deleteMapRuleInfo',
    ADMINFEATURE_getRuleLog: '/api/adminFeature/getRuleLog',
    ADMINFEATUER_getMapRuleInfo: '/api/adminFeature/getMapRuleInfo',
    // 特征服务 - 商户风控
    ADMINFEATURE_getMerchantRuleList: '/api/adminFeature/getMerchantRuleList',
    ADMINFEATURE_getMerchantList: '/api/adminFeature/getMerchantList',
    ADMINFEATURE_quote: '/api/adminFeature/quote'
};
export default apiUrl;